name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate build version
        id: info
        run: |
          formatted_date=$(date +'%Y.%m.%d')
          time=$(date +'%H%M%S')
          short_commit_id=$(git rev-parse --short HEAD)
          echo "build_version=${formatted_date}.${time}.${short_commit_id}" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Build
        run: docker build -t "ghcr.io/zaba505/backup/backup:${{ steps.info.outputs.build_version }}" - < Containerfile

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Github Container Registry
        run: docker push -a "ghcr.io/zaba505/backup/backup:${{ steps.info.outputs.build_version }}"